version: '2'

services:
  graph-service:
    container_name: graph-service
    build:
      context: ./graph-service
      dockerfile: Dockerfile
    ports:
      - 5001:80
  edmonds-karp-service:
    container_name: edmonds-karp-service
    build:
      context: ./edmonds-karp-service
      dockerfile: Dockerfile
    ports:
      - 5002:80
          
  bfs-service:
    container_name: bfs-service
    build:
      context: ./bfs-service
      dockerfile: Dockerfile
    ports:
      - 5003:80
      
  push-relabel-service:
    container_name: push-relabel-service
    build:
      context: ./push-relabel-service
      dockerfile: Dockerfile
    ports:
      - 5004:80