version: '2'

services:
  graph-service:
    container_name: graph-service
    build:
      context: .
      dockerfile: graph-service/Dockerfile
    ports:
      - 5001:80
  edmonds-karp-service:
    container_name: edmonds-karp-service
    build:
      context: .
      dockerfile: edmonds-karp-service/Dockerfile
    ports:
      - 5002:80
          
  bfs-service:
    container_name: bfs-service
    build:
      context: .
      dockerfile: graph-service/Dockerfile
    ports:
      - 5003:80