version: '3.8'

services:
  graph-service:
    build:
      context: ./graph-service
      dockerfile: Dockerfile

  edmonds-karp-service:
    build:
      context: ./edmonds-karp-service
      dockerfile: Dockerfile
     
  bfs-service:
    build:
      context: ./bfs-service
      dockerfile: Dockerfile
      
  push-relabel-service:
    build:
      context: ./push-relabel-service
      dockerfile: Dockerfile
      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8001:80
    
  